### ISSUE TITLE
Problem with capitalization

### ISSUE THREAD

**Issue by IkutiDev** [RPicster/Steam-Upload-GUI#1]
When using Steam Uploade GUI, if your .vdf scripts use for example PascalCase inside them, the program won't see the scripts or will cause overall problems.

When testing strings I believe we should just make file contents be all lower case, this should fix the problem.

Here's a PR with this fix #2

**Comment by RPicster** [comment]
Thanks for the report and the fixing PR 😁
I merged it and will upload a new release asap 🚨
