### ISSUE TITLE
Fails with spaces in path to ContentBuilder

### ISSUE THREAD

**Issue by Deozaan** [RPicster/Steam-Upload-GUI#3]
The UI can find the App ID VDF files without a problem, but when actually attempting to upload, the path is broken by any spaces found therein.

![SteamUploadGUI - Spaces Failure](https://user-images.githubusercontent.com/227734/203932780-4af47952-b397-4c26-8e5c-e88aa8e471f4.png)

**Comment by RPicster** [comment]
> The UI can find the App ID VDF files without a problem, but when actually attempting to upload, the path is broken by any spaces found therein.
> 
> ![SteamUploadGUI - Spaces Failure](https://user-images.githubusercontent.com/227734/203932780-4af47952-b397-4c26-8e5c-e88aa8e471f4.png)
> 

Thanks! I'll look into it!

**Comment by RPicster** [comment]
@Deozaan the issue is fixed in the latest release:
https://github.com/RPicster/Steam-Upload-GUI/releases/tag/v0.12

Thanks again for reporting it!
